"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function MfaEnrollPage() {
  const router = useRouter();
  const [qrCode, setQrCode] = useState("");
  const [secret, setSecret] = useState("");
  const [showSecret, setShowSecret] = useState(false);
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [verifying, setVerifying] = useState(false);

  useEffect(() => {
    fetch("/api/auth/mfa/enroll")
      .then((r) => r.json())
      .then((data) => {
        if (data.qrCode) {
          setQrCode(data.qrCode);
          setSecret(data.secret || "");
        } else {
          setError(data?.error || "Unable to start MFA setup.");
        }
      })
      .catch(() => setError("Network error. Please try again."))
      .finally(() => setLoading(false));
  }, []);

  async function handleVerify(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    setVerifying(true);
    try {
      const res = await fetch("/api/auth/mfa/verify", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ code: code.trim() }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        setError(data?.error || "Invalid code. Please try again.");
        return;
      }
      router.push(data.redirect || "/dashboard");
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setVerifying(false);
    }
  }

  return (
    <div className="min-h-[100dvh] bg-slate-50 flex flex-col safe-area-top safe-area-left safe-area-right">
      <nav className="border-b border-slate-200 bg-white">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center gap-2.5">
          <div className="flex items-center justify-center w-9 h-9 rounded-lg bg-[#0f172a] text-white text-xs font-bold">
            FTS
          </div>
          <span className="text-sm font-semibold text-slate-900">Schedule FlowTrack</span>
        </div>
      </nav>

      <div className="flex-1 flex items-center justify-center px-6 py-16">
        <div className="w-full max-w-sm">
          <div className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm">
            <div className="text-center mb-6">
              <h1 className="text-lg font-semibold text-slate-900">Set up two-step verification</h1>
              <p className="mt-1 text-xs text-slate-500">Owners are required to set this up once, right now.</p>
            </div>

            <details className="mb-4 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-600">
              <summary className="cursor-pointer font-medium text-slate-700">What is two-step verification?</summary>
              <p className="mt-2 leading-relaxed">
                Two-step verification adds a second, time-based code (generated by an app on your phone) on top of
                your password, so a stolen password alone can&apos;t be used to sign in to your business account.
              </p>
            </details>

            {loading ? (
              <div className="text-sm text-slate-500 text-center py-6">Loading setup...</div>
            ) : (
              <>
                <ol className="mb-5 space-y-2 text-xs text-slate-600 list-decimal list-inside">
                  <li>Open or install an authenticator app on your phone.</li>
                  <li>Scan the QR code below with the app.</li>
                  <li>Enter the six-digit code the app shows you.</li>
                  <li>Confirm setup.</li>
                  <li>Optionally add a backup authenticator on a second device.</li>
                </ol>

                <p className="mb-4 text-[11px] text-slate-500">
                  Examples of compatible apps: Google Authenticator, Microsoft Authenticator, Apple Passwords, Authy,
                  and 1Password.
                </p>

                {qrCode && (
                  <div className="mb-4 flex justify-center">
                    {/* eslint-disable-next-line @next/next/no-img-element -- Supabase returns a data: URI SVG, not a static asset next/image can optimize */}
                    <img src={qrCode} alt="Scan this QR code with your authenticator app" className="w-40 h-40" />
                  </div>
                )}

                <button
                  type="button"
                  onClick={() => setShowSecret((v) => !v)}
                  className="mb-4 text-xs font-medium text-blue-600 hover:text-blue-700"
                >
                  {showSecret ? "Hide manual setup key" : "Can't scan? Enter this code manually"}
                </button>
                {showSecret && (
                  <div className="mb-4 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-mono break-all text-slate-700">
                    {secret}
                  </div>
                )}

                <div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">
                  Do not share or screenshot this QR code or setup key — anyone who has it can generate your
                  sign-in codes.
                </div>

                <form onSubmit={handleVerify} className="space-y-4">
                  <div>
                    <label className="block text-xs font-medium text-slate-600 mb-1">Six-digit code</label>
                    <input
                      type="text"
                      inputMode="numeric"
                      value={code}
                      onChange={(e) => setCode(e.target.value)}
                      className="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm text-center tracking-widest focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="000000"
                      maxLength={6}
                    />
                  </div>

                  {error && (
                    <div className="rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-xs text-rose-700">
                      {error}
                    </div>
                  )}

                  <button
                    type="submit"
                    disabled={verifying}
                    className="w-full rounded-xl bg-[#0f172a] px-4 py-2.5 text-sm font-medium text-white hover:bg-slate-800 disabled:opacity-50 transition-colors"
                  >
                    {verifying ? "Verifying..." : "Verify and Continue"}
                  </button>
                </form>
              </>
            )}

            <p className="mt-6 text-center text-[11px] text-slate-400">
              This two-step verification setup applies to business owners only — it does not apply to employees.
            </p>
          </div>
          <div className="mt-6 text-center text-xs text-slate-500">
            <Link href="/login" className="hover:text-slate-700 transition-colors">
              Back to sign in
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
